POST http://localhost:27017/app/Pilote
Content-Type: application/json

{
  "Identifier" : "9586",
  "First name": "matt",
  "Last name": "jojo",
  "Next Mission": "03/12/2022",
  "Previous": "03/12/2022",
  "available": "yes"
}

###
